name: pipo
description: Clean code exploration Flutter project
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  dio: ^4.0.6
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.0.2
  freezed_annotation: ^2.2.0
  go_router: ^5.1.1
  json_annotation: ^4.7.0
  logger: ^1.1.0
  retrofit: ^3.3.1

dev_dependencies:
  build_runner: ^2.3.2
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.2.1
  json_serializable: ^6.5.4
  retrofit_generator: ^4.2.0

flutter:
  uses-material-design: true
  assets:
    - assets/config/config.json